app/models.py
# -*- coding: UTF-8 -*-
# author:liujiayu

from datetime import datetime
from app import db


class Model_name(db.Model):
    __tablename__="model"
    id = db.Column(db.Integer,primary_key=True)
    model_name = db.Column(db.String(100))
    create_time = db.Column(db.DateTime, index=True, default=datetime.now)


class Model_status(db.Model):
    __tablename__="model_status"
    id = db.Column(db.Integer,primary_key=True)
    model_name = db.Column(db.String(100))
    base_name = db.Column(db.String(100))
    to_branch = db.Column(db.String(100))
    status = db.Column(db.String(100))
    create_time = db.Column(db.DateTime, index=True, default=datetime.now)


if __name__ == '__main__':
    db.drop_all()
    db.create_all()

app/web/forms.py
# -*- coding: UTF-8 -*-
# author:liujiayu

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField
from wtforms.validators import DataRequired

class branchForm(FlaskForm):
    model = SelectMultipleField(
        label="下拉菜单",
        validators=[
            DataRequired("下拉菜单")
        ],
        render_kw={
            "class": "form-control selectpicker",
            "title": "请选择模块名称"
        },
        choices=[],
        default=1,
        coerce=int
    )
    branch_base = StringField(
        label="基础分支",
        validators=[
            DataRequired("请输入基础分支名称")
        ],
        render_kw={
            "class": "form-control",
            "placeholder": "基础分支名称"
        }
    )
    branch_to = StringField(
        label="目标分支",
        validators=[
            DataRequired("请输入目标分支名称")
        ],
        render_kw={
            "class": "form-control",
            "placeholder": "目标分支名称"
        }
    )

    submit = SubmitField(
        label="确认",
        render_kw={
            "class": "btn btn-primary"
        }

    )
class addForm(FlaskForm):
    model_name = StringField(
        label="模块名称",
        validators=[
            DataRequired("请输入模块名称")
        ],
        render_kw={
            "class": "form-control",
            "placeholder": "group/project"
        }
    )

    submit = SubmitField(
        label="确认",
        render_kw={
            "class": "btn btn-primary"
        }

    )

class delForm(FlaskForm):
    submit = SubmitField(
        label="返回",
        render_kw={
            "class": "btn btn-primary"
        }

    )

app/__init__.py
# -*- coding: UTF-8 -*-
# author:liujiayu
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config['SECRET_KEY'] = 'csrd_key'
app.config['SQLALCHEMY_DATABASE_URI'] = "xxxxx" #mysql+pymysql://user:password@ip:port/db_name
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.debug = True
db=SQLAlchemy(app)



from app.web import web as web_blueprint
app.register_blueprint(web_blueprint)

app/web/__init__.py
# -*- coding: UTF-8 -*-
# author:liujiayu
from flask import Blueprint

web = Blueprint("web",__name__)

import app.web.views

app/web/views.py
from flask import render_template, flash, redirect, url_for
from app.web.forms import branchForm, addForm, delForm
from gitlab_api import gitlabAPI
from . import web
from app.models import Model_name, Model_status
from app import db

@web.route('/list', methods=['GET','POST'])
def list():
    form = delForm()
    data = Model_status.query.all()
    if form.validate_on_submit():
        for i in data:
            db.session.delete(i)
            db.session.commit()
        return redirect(url_for("web.branch_manage"))
    return render_template("list.html",data=data,form=form)


@web.route('/', methods=['GET', 'POST'])
def branch_manage():
    form = branchForm()
    form.model.choices =[(v.id,v.model_name) for v in Model_name.query.all()]
    try:
        if form.validate_on_submit():
            data = form.data
            brch = gitlabAPI()
            model_dict = {}
            model_choose = {}  # {1: 'group1/project1', 2: 'group2/project2'}
            model_query = Model_name.query.all()
            for v in model_query:
                model_choose[v.id]=v.model_name
            for id in data["model"]:
                model_dict[id] = model_choose[id]
            for i in model_dict:
                ret = brch.make_branch(data["branch_to"], data["branch_base"], model_dict[i])
                brch.to_0_project(model_dict[i],data["branch_to"])
                if ret == True:
                    info = Model_status(
                        model_name=model_dict[i],
                        base_name=data["branch_base"],
                        to_branch=data["branch_to"],
                        status="成功"
                    )
                    db.session.add(info)
                    db.session.commit()

            return redirect(url_for("web.list"))
    except Exception as e:
        print(str(e))
        flash("错误：{}".format(str(e)), "err")

    return render_template("branch_manage.html", form=form)


@web.route('/branch_add', methods=['GET', 'POST'])
def branch_add():
    form = addForm()
    try:
        if form.validate_on_submit():
            data=form.data
            brch = gitlabAPI()
            ret=brch.get_project(data["model_name"])
            if ret:
                data_model=Model_name(model_name=data["model_name"])
                db.session.add(data_model)
                db.session.commit()
                flash("添加成功", "ok")
                return redirect(url_for("web.branch_manage"))
    except Exception as e:
        print(str(e))
        flash("错误：{}".format(str(e)), "err")
    return render_template("branch_add.html",form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Git工具</title>
    <link rel='stylesheet prefetch' href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <link rel='stylesheet prefetch' href="{{ url_for('static',filename='css/bootstrap-select.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/htmleaf-demo.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    {% block head %}{% endblock %}
</head>
<body>

<div id="wrapper">
    <div class="overlay"></div>

    <!-- Sidebar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                <a href="#">
                    Git工具
                </a>
            </li>
            <li>
                <a href="{{ url_for('web.branch_manage') }}"><i class="fa fa-fw fa-home"></i> 分支管理</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-home"></i> 代码行统计</a>
            </li>
            <!--<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-plus"></i> Dropdown
                    <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li class="dropdown-header">Dropdown heading</li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>
            </li>-->

        </ul>
    </nav>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <button type="button" class="hamburger is-closed animated fadeInLeft" data-toggle="offcanvas">
            <span class="hamb-top"></span>
            <span class="hamb-middle"></span>
            <span class="hamb-bottom"></span>
        </button>

        {% block content %}{% endblock %}

    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<script src="{{ url_for('static',filename='js/jquery.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap-select.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var trigger = $('.hamburger'),
            overlay = $('.overlay'),
            isClosed = false;

        trigger.click(function () {
            hamburger_cross();
        });

        function hamburger_cross() {

            if (isClosed == true) {
                overlay.hide();
                trigger.removeClass('is-open');
                trigger.addClass('is-closed');
                isClosed = false;
            } else {
                overlay.show();
                trigger.removeClass('is-closed');
                trigger.addClass('is-open');
                isClosed = true;
            }
        }

        $('[data-toggle="offcanvas"]').click(function () {
            $('#wrapper').toggleClass('toggled');
        });
    });
</script>


</body>
</html>

app/templates/branch_add.html
{% extends 'base.html' %}

{% block head %}
    <style>
        td {
            color: white;
        }
    </style>
{% endblock %}

{% block content %}
    {% for msg in get_flashed_messages(category_filter=["ok"]) %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> 添加成功 </h4>
            {{ msg }}
        </div>
    {% endfor %}
    {% for msg in get_flashed_messages(category_filter=["err"]) %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i> 添加失败 </h4>
            {{ msg }}
        </div>
    {% endfor %}
    <form method="post" class="form-horizontal" autocomplete="off">
        <fieldset>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="ds_host" style="color: white">添加模块名称</label>
                <div class="col-sm-4">
                    {{ form.model_name }}
                </div>
                <div>
                    {{ form.csrf_token }}
                    {{ form.submit }}
                    <a href="{{ url_for('web.branch_manage') }}" class="btn btn-default">取消</a>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

app/templates/branch_manage.html
{% extends 'base.html' %}


{% block content %}
    {% for msg in get_flashed_messages(category_filter=["ok"]) %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> 提交成功 </h4>
            {{ msg }}
        </div>
    {% endfor %}
    {% for msg in get_flashed_messages(category_filter=["err"]) %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i> 提交失败 </h4>
            {{ msg }}
        </div>
    {% endfor %}
    <form method="post" class="form-horizontal" autocomplete="off">
        <fieldset>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="ds_host" style="color: white">基于分支名称</label>
                <div class="col-sm-4">
                    {{ form.branch_base }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="ds_host" style="color: white">目标分支名称</label>
                <div class="col-sm-4">
                    {{ form.branch_to }}
                </div>
            </div>
            <!--<div class="form-group">
                <label class="col-sm-2 control-label" for="ds_host" style="color: white">保护分支类型</label>
                <div class="col-sm-4">

                </div>
            </div>-->
            <div class="form-group">
                <label class="col-sm-2 control-label" for="ds_host" style="color: white">选择模块名称</label>
                <div class="col-sm-4">
                    <div style="display: flex; justify-content: flex-start;">
                        {{ form.model }}
                        <div>
                            {{ form.csrf_token }}
                            {{ form.submit }}
                        </div>
                        <div>
                            <a href="{{ url_for('web.branch_add') }}" class="btn btn-default">增加模块</a>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
    <div style="margin-left: 11%">
        {% for log in log_list %}
        <b style="color: white;">{{ log }}</b><br>
        {% endfor %}
    </div>


{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h1 class="page-header">首页</h1>
        </div>
    </div>
</div>
{% endblock %}

app/templates/list.html
{% extends 'base.html' %}

{% block content %}
    <div style="display: flex; justify-content: flex-start;">
            <div  style="margin-left: 10%;width:50%;color: white;">
                <table class="table table-hover">
                    <tr>
                        <td>模块名</td>
                        <td>目标分支</td>
                        <td>基于分支</td>
                        <td>情况</td>
                    </tr>
                    {% for i in data %}
                        <tr>
                            <td>{{ i.model_name }}</td>
                            <td>{{ i.to_branch }}</td>
                            <td>{{ i.base_name }}</td>
                            <td>{{ i.status }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        <div style="margin-left: 20px">
            <form method="post">
                {{ form.csrf_token }}
                {{ form.submit }}
            </form>
        </div>
    </div>
{% endblock %}